on: [workflow_dispatch]
name: Deploy Service Bus Namespace

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Log into Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.ARM_DEPLOYER_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Namespace
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./service-bus/service-bus.bicep
        failOnStdErr: false